// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab1.DAL;

#nullable disable

namespace lab1.Migrations
{
    [DbContext(typeof(ITIDbContext))]
    [Migration("20251014194333_student-course-migrations")]
    partial class studentcoursemigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseDepartments", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentsDeptID")
                        .HasColumnType("int");

                    b.HasKey("CoursesId", "DepartmentsDeptID");

                    b.HasIndex("DepartmentsDeptID");

                    b.ToTable("CourseDepartments");
                });

            modelBuilder.Entity("ModelLayer.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CrsDuration")
                        .HasColumnType("int");

                    b.Property<string>("CrsName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CrsDuration = 4,
                            CrsName = "C#"
                        },
                        new
                        {
                            Id = 2,
                            CrsDuration = 3,
                            CrsName = "Java"
                        },
                        new
                        {
                            Id = 3,
                            CrsDuration = 5,
                            CrsName = "Python"
                        });
                });

            modelBuilder.Entity("ModelLayer.StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("Degree")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourse");
                });

            modelBuilder.Entity("lab1.Models.Departments", b =>
                {
                    b.Property<int>("DeptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("DeptName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("DeptID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DeptID = 1,
                            Capacity = 30,
                            DeptName = "CS",
                            Status = true
                        },
                        new
                        {
                            DeptID = 2,
                            Capacity = 30,
                            DeptName = "IS",
                            Status = true
                        },
                        new
                        {
                            DeptID = 3,
                            Capacity = 30,
                            DeptName = "IT",
                            Status = true
                        });
                });

            modelBuilder.Entity("lab1.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DeptID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeptID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CourseDepartments", b =>
                {
                    b.HasOne("ModelLayer.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lab1.Models.Departments", null)
                        .WithMany()
                        .HasForeignKey("DepartmentsDeptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModelLayer.StudentCourse", b =>
                {
                    b.HasOne("ModelLayer.Course", "Course")
                        .WithMany("CourseStudent")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lab1.Models.Student", "Student")
                        .WithMany("studentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("lab1.Models.Student", b =>
                {
                    b.HasOne("lab1.Models.Departments", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DeptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ModelLayer.Course", b =>
                {
                    b.Navigation("CourseStudent");
                });

            modelBuilder.Entity("lab1.Models.Departments", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("lab1.Models.Student", b =>
                {
                    b.Navigation("studentCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
